watch_path = "./input"
output_path = "./output"

root_tag = "root"

input_csv = false
input_excel = true
output_xml = false
output_json = true

[mappings]
column1 = "column1"
column2 = "extra.column2"
column3 = "extra.column3"
